### ISSUE TITLE
you should make a requirements.txt instead of showing it on the README file

### ISSUE THREAD

**Issue by apolyeti** [oliverpearce/handwritten-digits#1]
run
```bash
pip freeze > requirements.txt
```
while in your virtual environment to quickly grab all your packages and push it to the remote repository

**Comment by oliverpearce** [comment]
so true bestie

**Comment by Yelloo5191** [comment]
bro's the python pedant

**Comment by apolyeti** [comment]
Thank you for your responses

**Comment by apolyeti** [comment]
> bro's the python pedant

Just helping with open source contribution. Please be more respectful towards others next time, Mr. Yelloo5191.
